CREATE TABLE "companies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "subscription_plan" varchar NOT NULL,
  "status" varchar NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" varchar UNIQUE NOT NULL,
  "description" varchar
);

CREATE TABLE "role_permissions" (
  "role_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "positions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "description" text,
  "level" integer,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "status" varchar NOT NULL DEFAULT 'active',
  "last_login_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "departments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "employees" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "user_id" integer UNIQUE,
  "department_id" integer,
  "employee_code" varchar NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "nickname" varchar,
  "gender" varchar,
  "birth_date" date,
  "personal_email" varchar,
  "phone" varchar,
  "address" text,
  "emergency_contact_name" varchar,
  "emergency_contact_phone" varchar,
  "position_id" integer,
  "manager_employee_id" integer,
  "employment_type" varchar NOT NULL DEFAULT 'permanent',
  "employment_status" varchar NOT NULL DEFAULT 'active',
  "hire_date" date,
  "contract_start_date" date,
  "contract_end_date" date,
  "base_salary" decimal,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "employee_id" integer NOT NULL,
  "request_type" varchar NOT NULL,
  "status" varchar NOT NULL DEFAULT 'pending',
  "submitted_at" timestamp NOT NULL DEFAULT (now()),
  "approved_at" timestamp,
  "rejected_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "request_approvals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer NOT NULL,
  "approver_id" integer NOT NULL,
  "status" varchar NOT NULL,
  "comment" text,
  "action_at" timestamp
);

CREATE TABLE "leave_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer UNIQUE NOT NULL,
  "leave_type" varchar NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "reason" text
);

CREATE TABLE "ot_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer UNIQUE NOT NULL,
  "work_date" date NOT NULL,
  "hours" decimal NOT NULL,
  "reason" text
);

CREATE TABLE "reimbursement_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "request_id" integer UNIQUE NOT NULL,
  "amount" decimal NOT NULL,
  "description" text,
  "receipt_url" varchar,
  "receipt_status" varchar NOT NULL DEFAULT 'pending'
);

CREATE TABLE "attendance_records" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "employee_id" integer NOT NULL,
  "check_in_at" timestamp NOT NULL,
  "check_out_at" timestamp,
  "attendance_status" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "payrolls" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "employee_id" integer NOT NULL,
  "base_salary" decimal NOT NULL,
  "ot_amount" decimal NOT NULL DEFAULT 0,
  "deduction_amount" decimal NOT NULL DEFAULT 0,
  "net_salary" decimal NOT NULL,
  "payroll_month" integer NOT NULL,
  "payroll_year" integer NOT NULL,
  "generated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "ot_rules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "ot_type" varchar NOT NULL,
  "multiplier" decimal NOT NULL,
  "max_hours_per_day" decimal,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "work_rules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "work_start_time" time NOT NULL,
  "work_end_time" time NOT NULL,
  "break_minutes" integer DEFAULT 60,
  "late_grace_minutes" integer DEFAULT 15,
  "working_days" varchar,
  "working_types" varchar,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "public_holidays" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_code" varchar NOT NULL,
  "year" integer NOT NULL,
  "date" date NOT NULL,
  "name" varchar NOT NULL,
  "name_local" varchar,
  "is_paid" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "company_calendars" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "date" date NOT NULL,
  "name" varchar NOT NULL,
  "day_type" varchar NOT NULL,
  "is_paid" boolean NOT NULL DEFAULT true,
  "description" text,
  "created_by" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "message" text NOT NULL,
  "is_read" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer NOT NULL,
  "user_id" integer,
  "action" varchar NOT NULL,
  "module" varchar NOT NULL,
  "entity_id" integer,
  "old_value" jsonb,
  "new_value" jsonb,
  "ip_address" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "positions" ("company_id");

CREATE UNIQUE INDEX ON "positions" ("company_id", "name");

CREATE INDEX ON "users" ("company_id");

CREATE INDEX ON "users" ("email");

CREATE INDEX ON "departments" ("company_id");

CREATE UNIQUE INDEX ON "departments" ("company_id", "name");

CREATE INDEX ON "employees" ("company_id");

CREATE INDEX ON "employees" ("department_id");

CREATE INDEX ON "employees" ("user_id");

CREATE UNIQUE INDEX ON "employees" ("company_id", "employee_code");

CREATE INDEX ON "employees" ("employment_status");

CREATE INDEX ON "employees" ("employment_type");

CREATE INDEX ON "employees" ("contract_end_date");

CREATE INDEX ON "requests" ("company_id");

CREATE INDEX ON "requests" ("employee_id");

CREATE INDEX ON "requests" ("employee_id", "status");

CREATE INDEX ON "requests" ("company_id", "request_type", "status");

CREATE INDEX ON "request_approvals" ("request_id");

CREATE INDEX ON "request_approvals" ("approver_id");

CREATE INDEX ON "attendance_records" ("employee_id");

CREATE INDEX ON "attendance_records" ("employee_id", "check_in_at");

CREATE INDEX ON "attendance_records" ("company_id");

CREATE INDEX ON "payrolls" ("employee_id");

CREATE UNIQUE INDEX ON "payrolls" ("company_id", "employee_id", "payroll_year", "payroll_month");

CREATE UNIQUE INDEX ON "public_holidays" ("country_code", "date");

CREATE INDEX ON "public_holidays" ("country_code", "year");

CREATE UNIQUE INDEX ON "company_calendars" ("company_id", "date");

CREATE INDEX ON "notifications" ("user_id", "is_read");

CREATE INDEX ON "notifications" ("company_id");

CREATE INDEX ON "audit_logs" ("company_id");

CREATE INDEX ON "audit_logs" ("company_id", "module", "entity_id");

CREATE INDEX ON "audit_logs" ("created_at");

COMMENT ON COLUMN "companies"."status" IS 'active | suspended | cancelled';

COMMENT ON COLUMN "positions"."level" IS 'Hierarchy level: CEO=1, Manager=2, Staff=3';

COMMENT ON COLUMN "users"."status" IS 'active | inactive | locked';

COMMENT ON COLUMN "employees"."gender" IS 'male | female | other';

COMMENT ON COLUMN "employees"."employment_type" IS 'permanent | contract | intern | probation';

COMMENT ON COLUMN "employees"."employment_status" IS 'active | on_leave | terminated | resigned';

COMMENT ON COLUMN "requests"."request_type" IS 'leave | ot | reimbursement';

COMMENT ON COLUMN "requests"."status" IS 'pending | approved | rejected | cancelled';

COMMENT ON COLUMN "request_approvals"."status" IS 'pending | approved | rejected';

COMMENT ON COLUMN "leave_requests"."leave_type" IS 'annual | sick | personal | unpaid';

COMMENT ON COLUMN "reimbursement_requests"."receipt_status" IS 'pending | submitted | verified';

COMMENT ON COLUMN "attendance_records"."attendance_status" IS 'present | absent | late | half_day';

COMMENT ON COLUMN "payrolls"."payroll_month" IS '1–12';

COMMENT ON COLUMN "ot_rules"."ot_type" IS 'workday | holiday | weekend';

COMMENT ON COLUMN "ot_rules"."multiplier" IS '1.5x | 2x | 3x';

COMMENT ON COLUMN "work_rules"."working_days" IS 'mon,tue,wed,thu,fri';

COMMENT ON COLUMN "work_rules"."working_types" IS 'OFFICE, WFH';

COMMENT ON COLUMN "public_holidays"."country_code" IS 'ISO 3166-1 alpha-2: TH, SG, MY, PH';

COMMENT ON COLUMN "public_holidays"."name_local" IS 'Local language name from API';

COMMENT ON COLUMN "company_calendars"."day_type" IS 'extra_holiday | special_workday | override';

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "positions" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "departments" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("position_id") REFERENCES "positions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employees" ADD FOREIGN KEY ("manager_employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "requests" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "requests" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "request_approvals" ADD FOREIGN KEY ("request_id") REFERENCES "requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "request_approvals" ADD FOREIGN KEY ("approver_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leave_requests" ADD FOREIGN KEY ("request_id") REFERENCES "requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ot_requests" ADD FOREIGN KEY ("request_id") REFERENCES "requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reimbursement_requests" ADD FOREIGN KEY ("request_id") REFERENCES "requests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attendance_records" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attendance_records" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payrolls" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payrolls" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ot_rules" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "work_rules" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "company_calendars" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "company_calendars" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
